- name: Ensure legacy workspace directory
  file:
    path: '{{ ansible_user_dir }}/workspace'
    state: directory

- name: Build and Install nasm
  shell:
    cmd: |
      set -e
      set -x
      cd $WORKSPACE
      curl https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/nasm-2.16.01.tar.gz | tar -xz
      cd nasm*
      ./autogen.sh
      ./configure
      make nasm
      sudo install -c nasm /usr/bin/nasm
    executable: /bin/bash
    chdir: '{{ ansible_user_dir }}/workspace'
  environment: '{{ zuul | zuul_legacy_vars }}'

- name: Build and Install ISA-L
  shell:
    cmd: |
      set -e
      set -x
      cd $WORKSPACE
      git clone https://github.com/intel/isa-l.git
      cd isa-l
      ./autogen.sh
      ./configure
      make
      sudo make install
    executable: /bin/bash
    chdir: '{{ ansible_user_dir }}/workspace'
  environment: '{{ zuul | zuul_legacy_vars }}'
